[package]
name = "custom_observer"
version = "0.1.0"
edition = "2024"

[dependencies]
scrapely = { workspace = true }
async-trait = "0.1.89"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.24.0"
anyhow = "1.0"
