[package]
name = "advanced"
version = "0.1.0"
edition = "2021"

[dependencies]
scrapely = { workspace = true }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.24"
tokio-util = "0.7"
regex = "1.12.2"