[package]
name = "quotes"
version = "0.1.0"
edition = "2024"

[dependencies]
scrapely = { workspace = true }

anyhow = "1.0.100"
regex = "1.12.2"
reqwest = { version = "0.12.24", features = ["json"] }
scraper = "0.24"
tokio = { version = "1.48.0", features = ["full"] }
